### ISSUE TITLE
Support identifiers for calendars in config

### ISSUE THREAD

**Issue by hughbris** [hughbris/grav-plugin-fullcalendar#4]
These would be used in shortcodes instead of the long calendar ID strings (or perhaps paths) that need to be added.

Two benefits:

* much simpler to embed
* allows per-environment switching of underlying calendar IDs, i.e. using test/prod calendars in the corresponding environment.

Draft frontmatter:

```yaml
fullcalendar:
  calendars:
    bookings:
      id: XX_CALENDAR_ID_HERE
      # other shortcode parameters could also be supported here in future to make them simpler to embed ..
      # ... e.g. type: gcal
```

then the shortcode could be something like : `[monthcalendar name="bookings" /]`.
